"use client"

import { X } from "lucide-react"
import { Button } from "@/components/ui/button"

interface AboutDialogProps {
  open: boolean
  onClose: () => void
}

export function AboutDialog({ open, onClose }: AboutDialogProps) {
  if (!open) return null

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      onClick={(e) => { if (e.target === e.currentTarget) onClose() }}
    >
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" aria-hidden />

      {/* Panel */}
      <div className="relative z-10 w-full max-w-lg rounded-xl bg-white shadow-xl overflow-y-auto max-h-[90vh]">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-border px-6 py-4">
          <h2 className="text-lg font-semibold text-heading">About Bible Exegesis Explorer</h2>
          <button
            onClick={onClose}
            className="rounded-md p-1 text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
            aria-label="Close about"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Body */}
        <div className="px-6 py-5 space-y-6 text-sm text-left text-foreground">

          <section className="space-y-2">
            <h3 className="font-semibold text-heading text-base">Part of Paul's Bible Tools</h3>
            <p>
              Bible Exegesis Explorer is part of a collection of free Bible study tools built by Paul.
              You can find the full collection at{" "}
              <a
                href="https://paulpowell.cc/"
                target="_blank"
                rel="noopener noreferrer"
                className="font-medium text-heading underline decoration-gold underline-offset-2 hover:text-olive"
              >
                Paul's Bible Tools
              </a>
              , also linked from the menu in the top-right corner of this page.
            </p>
          </section>

          <section className="space-y-2">
            <h3 className="font-semibold text-heading text-base">How this app works</h3>
            <p>
              When you enter a passage reference, the app first looks up the exact wording of that passage from
              the English Standard Version (ESV) — the same trusted Bible translation used in print and study
              editions.
            </p>
            <p>
              That passage text is then handed to <span className="font-medium text-heading">Claude</span>, an AI
              assistant made by a company called Anthropic. You can think of Claude as a very well-read research
              assistant: it has been trained on an enormous amount of text, including biblical scholarship, and it
              can read a passage and write out an explanation the same way a knowledgeable person would — just
              much faster.
            </p>
            <p>
              Claude reads the passage and picks out the words that carry the most theological weight, then writes
              a short explanation of what the original Hebrew or Greek word behind each one really meant. When you
              click a highlighted word, that explanation is what you're reading — generated by Claude, in real
              time, based on the actual Bible text for that verse.
            </p>
          </section>

        </div>

        {/* Footer */}
        <div className="border-t border-border px-6 py-4 flex justify-end">
          <Button variant="outline" size="sm" onClick={onClose}>Got it</Button>
        </div>
      </div>
    </div>
  )
}
